apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-next-timestamp-authority
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-next-timestamp-authority
    app.kubernetes.io/part-of: timestamp-authority
  name: release-next-timestamp-authority
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app.kubernetes.io/instance: release-next-timestamp-authority
status:
  loadBalancer: {}
